import = ["~/.config/alacritty/themes/tokyo-night.toml"]

working_directory = "None"
live_config_reload = true

[env]
TERM = "alacritty"
GTK_IM_MODULE = "fcitx5"
QT_IM_MODULE = "fcitx5"
XMODIFIERS = "@im=fcitx5"
LANG = "en_US.UTF-8"

[window]
opacity = 0.8
title = "alacritty"
dynamic_title = false
class = { instance = "alacritty", general = "alacritty" }

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

